
# config.py

BINANCE_API_KEY = 'veiqd07BuRmMlxy3eeRLLKNyDnFrIphTcqgSM7XTRUCzQWTyqxK4sPtfVZioaVHi'
BINANCE_API_SECRET = 'N4myBDNkkD203gxxpo8NLQgdZxdvzm7N7PpBjBU0DiTtctTLaFQEVev51N4P5R5g'

# Telegram API keys
#TELEGRAM_BOT_TOKEN = ''
#TELEGRAM_CHAT_ID = ''


# List of futures trading pairs (symbols)
symbols = [
    '1INCHUSDT', '1000SATSUSDT', 'ACEUSDT', 'ACHUSDT', 'ADAUSDT', 'AIUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ALTUSDT', 'ANKRUSDT',
    'ANTUSDT', 'APEUSDT', 'APTUSDT', 'ARBUSDT', 'ARKUSDT', 'ARPAUSDT', 'ARUSDT', 'ASTRUSDT', 'ATAUSDT', 'AUDIOUSDT',
    'AVAXUSDT', 'BADGERUSDT', 'BALUSDT', 'BANDUSDT', 'BAKEUSDT', 'BATUSDT', 'BEAMXUSDT', 'BELUSDT', 'BCHUSDT', 'BICOUSDT',
    'BLURUSDT', 'BLZUSDT', 'BNBUSDT', 'BTCUSDT', 'CAKEUSDT', 'CELOUSDT', 'CELRUSDT', 'CHRUSDT', 'CKBUSDT',
    'COMPUSDT', 'COTIUSDT', 'CRVUSDT', 'CTKUSDT', 'CTSIUSDT', 'CYBERUSDT', 'DASHUSDT', 'DENTUSDT', 'DGBUSDT',
    'DOGEUSDT', 'DOTUSDT', 'DUSKUSDT', 'DYMUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'FETUSDT',
    'FILUSDT', 'FLMUSDT', 'FTMUSDT', 'FXSUSDT', 'GALUSDT', 'GLMRUSDT', 'GRTUSDT', 'GUSDUSDT', 'HBARUSDT', 'HIGHUSDT',
    'HOTUSDT', 'IOTXUSDT', 'IOSTUSDT', 'IOTAUSDT', 'JASMYUSDT', 'JTOUSDT', 'JUPUSDT', 'KAVAUSDT', 'KEYUSDT', 'KNCUSDT',
    'KSMUSDT', 'LDOUSDT', 'LINKUSDT', 'LINAUSDT', 'LITUSDT', 'LPTUSDT', 'LSKUSDT', 'LTCUSDT', 'LUNAUSDT', 'MANTAUSDT',
    'MANAUSDT', 'MASKUSDT', 'MATICUSDT', 'MDTUSDT', 'MEMEUSDT', 'MKRUSDT', 'MLNUSDT', 'MTHUSDT', 'MTLUSDT', 'NANOUSDT',
    'NFTUSDT', 'NKNUSDT', 'NMRUSDT', 'NTRNUSDT', 'NUUSDT', 'OCEANUSDT', 'OGNUSDT', 'OMGUSDT', 'ONEUSDT', 'ONTUSDT',
    'ORDIUSDT', 'OXTUSDT', 'PERPUSDT', 'POLSUSDT', 'POWRUSDT', 'PROUSDT', 'QKCUSDT', 'QTUMUSDT', 'REEFUSDT', 'RENUSDT',
    'REVVUSDT', 'RLCUSDT', 'ROSEUSDT', 'RSRUSDT', 'RVNUSDT', 'RUNEUSDT', 'SANDUSDT', 'SCRTUSDT', 'SEIUSDT', 'SKLUSDT',
    'SLPUSDT', 'SOLUSDT', 'SPELLUSDT', 'SRMUSDT', 'SXPUSDT', 'STMXUSDT', 'STORJUSDT', 'STPTUSDT', 'STXUSDT',
    'SUNUSDT', 'SUPERUSDT', 'SUSHIUSDT', 'SXPUSDT', 'TCTUSDT', 'TLMUSDT', 'TWTUSDT', 'UMAUSDT', 'UNFIUSDT', 'UNIUSDT',
    'USKOUSDT', 'VETUSDT', 'VRAUSDT', 'WAVESUSDT', 'WLDUSDT', 'WOAUSDT', 'WOOUSDT',
    'XAIUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'XVGUSDT', 'XVSUSDT', 'YFIUSDT', 'ZECUSDT',
    'ZENUSDT', 'ZILUSDT', 'ZRXUSDT'
]

# Time interval for fetching historical data
time_interval = '15m'  # You can change this to '4h', '1d', etc.
